/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_awinic_atouchdect_aw_jni_i2c_jni */

#ifndef _Included_com_awinic_atouchdect_aw_jni_i2c_jni
#define _Included_com_awinic_atouchdect_aw_jni_i2c_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_awinic_atouchdect_aw_jni_i2c_jni
 * Method:    IICWriteRead
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_awinic_atouchdect_aw_1jni_i2c_1jni_IICWriteRead
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
